springdoc:
  swagger-ui:
    path: /swagger
    operations-sorter: method
    syntax-highlight:
      activated: true
    tags-sorter: alpha
  writer-with-order-by-keys: true

spring:
  profiles:
    active: dev
  config:
    import: optional:file:src/main/resources/r2dbc.yml
  main:
    web-application-type: reactive

logging:
  file:
    name: logs/moticlubs_service.log

server:
  error:
    whitelabel:
      enabled: false
  port: 8002
  forward-headers-strategy: framework
