app:
  context-path: ~

springdoc:
  swagger-ui:
    path: /swagger
    operations-sorter: method
    syntax-highlight:
      activated: true
    tags-sorter: alpha
    config-url: ${app.context-path}/v3/api-docs/swagger-config
    url: ${app.context-path}/v3/api-docs
    disable-swagger-default-url: true
  writer-with-order-by-keys: true

spring:
  webflux:
    base-path: ${app.context-path}
    static-path-pattern: /static/**
  profiles:
    active: dev
  config:
    import: optional:file:src/main/resources/secrets.yml
  main:
    web-application-type: reactive
  boot:
    admin:
      client:
        url: http://localhost:8003/spring-admin
        enabled: true
        auto-registration: true
        instance:
          name: MotiClubs-Service

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    env:
      show-values: when_authorized
  info:
    env:
      enabled: true

logging:
  file:
    name: logs/moticlubs_service.log

server:
  error:
    whitelabel:
      enabled: false
  port: 8002
  forward-headers-strategy: framework
