springdoc:
  swagger-ui:
    path: /swagger
    operations-sorter: method
    syntax-highlight:
      activated: true
    tags-sorter: alpha
  writer-with-order-by-keys: true

spring:
  profiles:
    active: dev
  config:
    import: optional:file:src/main/resources/r2dbc.yml
  main:
    web-application-type: reactive
  boot:
    admin:
      client:
        url: http://localhost:8003
        enabled: true
        auto-registration: true
        instance:
          name: MotiClubs-Service

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    env:
      show-values: when_authorized
  info:
    env:
      enabled: true

logging:
  file:
    name: logs/moticlubs_service.log

server:
  error:
    whitelabel:
      enabled: false
  port: 8002
  forward-headers-strategy: framework
